import {auth,db,ref,onValue,onAuthStateChanged} from './firebase.js';
import {acceptConnection,declineConnection,disconnect} from './connections.js';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let installed=false,profiles={},connections={},stopProfiles=null,stopConnections=null;
const toast=m=>{const el=document.getElementById('toast');if(!el)return;el.textContent=m;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)};
const cleanup=()=>{stopProfiles?.();stopConnections?.();stopProfiles=stopConnections=null};
function injectButton(){const explore=document.getElementById('explorePeopleButton');if(!explore||document.getElementById('connectionsButton'))return;const btn=document.createElement('button');btn.id='connectionsButton';btn.type='button';btn.textContent='Connections';btn.className='secondary-action';btn.addEventListener('click',renderConnections);explore.parentElement?.appendChild(btn)}
function renderConnections(){const content=document.getElementById('content'),title=document.getElementById('viewTitle'),panel=document.getElementById('conversationPanel');if(!content||!auth.currentUser)return;document.body.classList.remove('chat-open');title.textContent='Connections';panel.innerHTML='<div class="conversation-empty"><div class="empty-orb">M</div><h2>Connections</h2><p>Manage your real Main connections and requests.</p></div>';content.innerHTML='<button class="back-link" id="connectionsBack" type="button">← Chats</button><div class="connection-tabs" role="tablist"><button class="connection-tab active" data-mode="incoming">Requests</button><button class="connection-tab" data-mode="outgoing">Sent</button><button class="connection-tab" data-mode="connected">Connected</button></div><div id="connectionList"><div class="empty-state"><strong>Loading connections…</strong><span>Connecting to Main.</span></div></div>';
 document.getElementById('connectionsBack').onclick=()=>{cleanup();document.querySelector('[data-view="chats"]')?.click()};
 let mode='incoming';const list=document.getElementById('connectionList');
 const draw=()=>{const me=auth.currentUser.uid;let items=Object.values(connections).filter(c=>c&&c.userA&&c.userB).map(c=>{const uid=c.userA===me?c.userB:c.userA;return {...c,uid,profile:profiles[uid]}}).filter(c=>c.profile);if(mode==='incoming')items=items.filter(c=>c.status==='pending'&&c.requestedBy!==me);if(mode==='outgoing')items=items.filter(c=>c.status==='pending'&&c.requestedBy===me);if(mode==='connected')items=items.filter(c=>c.status==='connected');list.innerHTML=items.length?items.map(c=>`<article class="connection-card"><span class="chat-avatar">${esc((c.profile.displayName||'M').charAt(0).toUpperCase())}</span><div class="chat-main"><strong class="chat-name">${esc(c.profile.displayName||'Main user')}</strong><span class="chat-preview">${c.profile.mood?esc(c.profile.mood):'Main user'}</span></div><div class="connection-actions">${mode==='incoming'?'<button class="connect-action accept" data-action="accept">Accept</button><button class="connect-action decline" data-action="decline">Decline</button>':mode==='outgoing'?'<span class="connection-state">Pending</span>':'<button class="connect-action disconnect" data-action="disconnect">Disconnect</button>'}</div></article>`).join(''):'<div class="empty-state"><strong>${mode==='incoming'?'No connection requests':mode==='outgoing'?'No pending requests':'No connections yet'}</strong><span>${mode==='incoming'?'When someone connects with you, the request will appear here.':mode==='outgoing'?'People you connect with will appear here until they respond.':'Your accepted connections will appear here.'}</span></div>';list.querySelectorAll('[data-action]').forEach(btn=>btn.onclick=async()=>{const card=btn.closest('.connection-card'),uid=card?.dataset.uid||items.find(c=>c.profile.displayName===card?.querySelector('.chat-name')?.textContent)?.uid;if(!uid)return;btn.disabled=true;try{if(btn.dataset.action==='accept')await acceptConnection(uid);else if(btn.dataset.action==='decline')await declineConnection(uid);else await disconnect(uid);toast(btn.dataset.action==='accept'?'Connected.':btn.dataset.action==='decline'?'Request declined.':'Disconnected.')}catch(e){toast(e.message||'Connection update failed')}finally{btn.disabled=false}});list.querySelectorAll('.connection-card').forEach((card,i)=>{if(items[i])card.dataset.uid=items[i].uid})};
 stopProfiles=onValue(ref(db,'publicProfiles'),s=>{profiles=s.val()||{};draw()});stopConnections=onValue(ref(db,`connectionsByUser/${auth.currentUser.uid}`),s=>{connections=s.val()||{};draw()});document.querySelectorAll('.connection-tab').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.connection-tab').forEach(x=>x.classList.toggle('active',x===b));draw()})}
function install(){if(installed)return;installed=true;const observer=new MutationObserver(injectButton);observer.observe(document.getElementById('content')||document.body,{childList:true,subtree:true});injectButton()}
onAuthStateChanged(auth,u=>{if(u)install();else{installed=false;cleanup()}});