import { auth, db, ref, set, onValue, onAuthStateChanged } from './firebase.js';
const connectionId=(a,b)=>[a,b].sort().join('_');
const root=id=>ref(db,`connections/${id}`);
const stateFor=(a,b)=>ref(db,`connectionsByUser/${a}/${b}`);
async function setConnection(a,b,status,requestedBy=''){const id=connectionId(a,b),payload={id,userA:a,userB:b,status,requestedBy,updatedAt:Date.now()};await set(root(id),payload);await set(stateFor(a,b),payload);await set(stateFor(b,a),payload)}
export async function connectTo(uid){const me=auth.currentUser;if(!me||!uid||uid===me.uid)throw new Error('Invalid connection.');await setConnection(me.uid,uid,'pending',me.uid)}
export async function acceptConnection(uid){const me=auth.currentUser;if(!me||!uid)throw new Error('Invalid connection.');await setConnection(me.uid,uid,'connected',me.uid)}
export async function declineConnection(uid){const me=auth.currentUser;if(!me||!uid)throw new Error('Invalid connection.');await setConnection(me.uid,uid,'declined',me.uid)}
export async function disconnect(uid){const me=auth.currentUser;if(!me||!uid)throw new Error('Invalid connection.');const id=connectionId(me.uid,uid);await set(root(id),null);await set(stateFor(me.uid,uid),null);await set(stateFor(uid,me.uid),null)}
export function watchConnection(uid,cb){const me=auth.currentUser;if(!me||!uid)return ()=>{};return onValue(stateFor(me.uid,uid),s=>cb(s.val()||null))}
function toast(message){const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(window.__mainToast);window.__mainToast=setTimeout(()=>el.classList.remove('show'),2400)}
function label(status,requestedBy,me){if(status==='connected')return 'Connected';if(status==='pending')return requestedBy===me?'Pending':'Accept';return 'Connect'}
async function readConnection(uid){return new Promise(resolve=>{let done=false;const finish=v=>{if(done)return;done=true;resolve(v)};const unsub=onValue(stateFor(auth.currentUser.uid,uid),s=>{finish(s.val()||null);unsub()},{onlyOnce:true});setTimeout(()=>finish(null),4000)})}
function observeExplore(){const list=document.getElementById('exploreList');if(!list)return;const scan=()=>list.querySelectorAll('[data-user]').forEach(card=>{const uid=card.dataset.user;if(!uid||uid===auth.currentUser?.uid||card.querySelector('.connect-action'))return;const btn=document.createElement('button');btn.type='button';btn.className='connect-action';btn.textContent='Connect';btn.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();try{const state=await readConnection(uid);if(state?.status==='connected'){toast('Connected');return}if(state?.status==='pending'&&state.requestedBy!==auth.currentUser.uid){await acceptConnection(uid);toast('Connected.')}else{await connectTo(uid);toast('Connection request sent.')}}catch(err){toast(err.message||'Connection update failed')}});card.appendChild(btn);watchConnection(uid,state=>{btn.textContent=label(state?.status,state?.requestedBy,auth.currentUser?.uid);btn.dataset.status=state?.status||'none'})});scan();new MutationObserver(scan).observe(list,{childList:true,subtree:true})}
function install(){if(window.__mainConnectionsInstalled)return;window.__mainConnectionsInstalled=true;document.addEventListener('click',async e=>{const card=e.target.closest?.('[data-user]');if(!card||e.target.closest('.connect-action'))return;const uid=card.dataset.user,me=auth.currentUser?.uid;if(!me||!uid||uid===me)return;e.preventDefault();e.stopImmediatePropagation();try{const state=await readConnection(uid);if(state?.status==='connected'){if(typeof card.onclick==='function')card.onclick();return}if(state?.status==='pending'&&state.requestedBy!==me){await acceptConnection(uid);toast('Connected.');return}await connectTo(uid);toast('Connection request sent.')}catch(err){toast(err.message||'Connection update failed')}},true);setInterval(observeExplore,800)}
onAuthStateChanged(auth,user=>{if(user)install()});if(auth.currentUser)install();
