import {auth,db,ref,onValue,get} from './firebase.js';
import {createGroup,watchMessages,sendMessage,markRead,markTyping} from './chat-service.js';
let installed=false,profiles={},connections={},stopProfiles=null,stopConnections=null,stopGroup=null,typingTimer=null;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{const e=document.getElementById('toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2400)};
const stopChat=()=>{stopGroup?.();stopGroup=null;clearTimeout(typingTimer)};
function inject(){const heading=document.querySelector('.section-heading');if(!heading||document.getElementById('newGroupButton'))return;const b=document.createElement('button');b.id='newGroupButton';b.type='button';b.className='secondary-action';b.textContent='New group';b.onclick=renderCreateGroup;heading.appendChild(b)}
function watch(){if(!auth.currentUser)return;stopProfiles?.();stopConnections?.();stopProfiles=onValue(ref(db,'publicProfiles'),s=>{profiles=s.val()||{};inject()});stopConnections=onValue(ref(db,`connectionsByUser/${auth.currentUser.uid}`),s=>{connections=s.val()||{};inject()})}
function install(){if(installed)return;installed=true;new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});document.getElementById('content')?.addEventListener('click',interceptChat,true);watch();auth.onAuthStateChanged?.(u=>u?watch():null)}
function connectedPeople(){return Object.values(connections).filter(c=>c?.status==='connected').map(c=>profiles[c.userA===auth.currentUser.uid?c.userB:c.userA]).filter(Boolean)}
function renderCreateGroup(){stopChat();document.body.classList.remove('chat-open');document.getElementById('viewTitle').textContent='New group';const content=document.getElementById('content'),panel=document.getElementById('conversationPanel');panel.innerHTML='<div class="conversation-empty"><div class="empty-orb">M</div><h2>Create a group</h2><p>Add people you are connected with to a real group conversation.</p></div>';content.innerHTML='<button class="back-link" id="groupBack">← Chats</button><div class="group-form"><label for="groupName">Group name</label><input id="groupName" maxlength="80" placeholder="Group name"><p class="section-label">Connected people</p><div id="groupMembers"></div><button id="createGroupSubmit" class="primary-button" type="button">Create group</button></div>';document.getElementById('groupBack').onclick=()=>window.dispatchEvent(new CustomEvent('main:navigate',{detail:'chats'}));const list=document.getElementById('groupMembers'),people=connectedPeople();list.innerHTML=people.length?people.map(u=>`<label class="group-person"><input type="checkbox" value="${esc(u.uid)}"><span class="chat-avatar small-avatar">${esc((u.displayName||'M').charAt(0).toUpperCase())}</span><span class="chat-main"><strong class="chat-name">${esc(u.displayName||'Main user')}</strong><span class="chat-preview">${u.mood?esc(u.mood):'Connected'}</span></span></label>`).join(''):'<div class="empty-state"><strong>No connections yet</strong><span>Connect with people before creating a group.</span></div>';document.getElementById('createGroupSubmit').onclick=async()=>{const name=document.getElementById('groupName').value.trim(),members=[...list.querySelectorAll('input:checked')].map(i=>i.value),b=document.getElementById('createGroupSubmit');b.disabled=true;try{const id=await createGroup(name,members);toast('Group created.');window.dispatchEvent(new CustomEvent('main:open-group',{detail:id}))}catch(e){toast(e.message||'Could not create group.')}finally{b.disabled=false}}}
function interceptChat(e){const card=e.target.closest?.('[data-chat]');if(!card)return;const chatId=card.dataset.chat;if(!chatId)return;get(ref(db,`chats/${chatId}`)).then(s=>{const chat=s.val();if(chat?.type==='group'){e.preventDefault();e.stopPropagation();openGroup(chatId,chat)}}).catch(()=>{})}
function openGroup(chatId,chat){stopChat();document.body.classList.add('chat-open');const panel=document.getElementById('conversationPanel');panel.innerHTML=`<div class="live-chat"><header class="chat-header"><button class="icon-button" id="groupClose" aria-label="Back">←</button><div class="chat-avatar small-avatar">G</div><div class="chat-identity"><strong>${esc(chat.name||'Group')}</strong><small>${Object.keys(chat.members||{}).length} members</small></div><button class="icon-button" id="groupInfo" aria-label="Group information">⋮</button></header><div class="messages" id="groupMessages"><div class="empty-state"><strong>Loading messages…</strong></div></div><form class="composer" id="groupMessageForm"><button type="button" class="icon-button" id="groupEmoji" aria-label="Emoji">☺</button><input id="groupMessageInput" autocomplete="off" maxlength="4000" placeholder="Message" aria-label="Message"><button class="send-button" type="submit" aria-label="Send">➤</button></form></div>`;document.getElementById('groupClose').onclick=()=>{document.body.classList.remove('chat-open');window.dispatchEvent(new CustomEvent('main:navigate',{detail:'chats'}))};document.getElementById('groupInfo').onclick=()=>showGroupInfo(chat);document.getElementById('groupEmoji').onclick=()=>toast('Emoji picker is not enabled yet.');const messages=document.getElementById('groupMessages');stopGroup=watchMessages(chatId,items=>{messages.innerHTML=items.length?items.map(m=>{const sender=profiles[m.senderId]?.displayName||'Main user';return `<div class="message-row ${m.senderId===auth.currentUser.uid?'mine':''}"><div class="message-bubble">${m.senderId!==auth.currentUser.uid?`<strong class="group-sender">${esc(sender)}</strong>`:''}${esc(m.text)}<small>${m.createdAt?new Date(m.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Sending…'} ${m.senderId===auth.currentUser.uid?(m.readBy&&Object.keys(m.readBy).length>1?'✓✓':'✓'):''}</small></div></div>`}).join(''):'<div class="empty-state"><strong>No messages yet</strong><span>Send the first message to this group.</span></div>';const last=items.at(-1);if(last&&last.senderId!==auth.currentUser.uid)markRead(chatId,last.id).catch(()=>{});messages.scrollTop=messages.scrollHeight});document.getElementById('groupMessageForm').onsubmit=async e=>{e.preventDefault();const i=document.getElementById('groupMessageInput'),text=i.value.trim();if(!text)return;i.disabled=true;try{await sendMessage(chatId,text);i.value='';await markTyping(chatId,false)}catch(err){toast(err.message||'Message could not be sent.')}finally{i.disabled=false;i.focus()}};document.getElementById('groupMessageInput').oninput=()=>{markTyping(chatId,true).catch(()=>{});clearTimeout(typingTimer);typingTimer=setTimeout(()=>markTyping(chatId,false).catch(()=>{}),1200)}}
function showGroupInfo(chat){const people=Object.keys(chat.members||{}).map(uid=>profiles[uid]?.displayName||'Main user');toast(`${chat.name||'Group'} • ${people.length} members`)}
window.addEventListener('main:open-group',e=>get(ref(db,`chats/${e.detail}`)).then(s=>{const c=s.val();if(c?.type==='group')openGroup(e.detail,c)}));
if(auth)install();
