import { auth, firestore, doc, getDoc, updateDoc, setDoc, firestoreServerTimestamp } from './firebase.js';
import { updateUserProfile } from './firestore-service.js';
import { uploadMedia } from './media-service.js';

const esc = value => String(value ?? '').replace(/[&<>\"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '\"':'&quot;', "'":'&#39;' }[c]));
const toast = message => { const el = document.getElementById('toast'); if (!el) return; el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 2400); };
let current = null;
async function loadProfile() { if (!auth?.currentUser || !firestore) return null; const snapshot = await getDoc(doc(firestore, 'users', auth.currentUser.uid)); return snapshot.exists() ? snapshot.data() : null; }
async function renderProfile() {
  current = await loadProfile(); if (!current) return toast('Profile is not available yet.');
  const content = document.getElementById('content'); const panel = document.getElementById('conversationPanel'); if (!content) return;
  document.getElementById('viewTitle').textContent = 'Profile & settings'; document.body.classList.remove('chat-open'); panel.innerHTML = '<div class="conversation-empty"><div class="empty-orb">M</div><h2>Your profile</h2><p>Edit your public identity and privacy preferences.</p></div>';
  content.innerHTML = `<div class="profile-card"><div class="profile-avatar" id="profileAvatar">${current.photoCID ? `<img src="https://gateway.pinata.cloud/ipfs/${encodeURIComponent(current.photoCID)}" alt="Profile photo">` : esc((current.displayName || 'M').charAt(0).toUpperCase())}</div><input id="profilePhotoInput" type="file" accept="image/jpeg,image/png,image/webp" hidden><button class="secondary-action" id="changeProfilePhoto">Change photo</button><label for="profileDisplayName">Display name</label><input id="profileDisplayName" maxlength="80" value="${esc(current.displayName || '')}"><label for="profileUsername">Username</label><input id="profileUsername" maxlength="32" value="${esc(current.username || '')}"><label for="profileBio">Bio</label><textarea id="profileBio" maxlength="160">${esc(current.bio || '')}</textarea><button class="primary-button" id="saveProfile">Save profile</button><hr><h3>Privacy</h3><label><input type="checkbox" id="privacyLastSeen" ${current.privacy?.lastSeen !== false ? 'checked' : ''}> Show last seen</label><label><input type="checkbox" id="privacyOnline" ${current.privacy?.online !== false ? 'checked' : ''}> Show online status</label><label><input type="checkbox" id="privacyReadReceipts" ${current.privacy?.readReceipts !== false ? 'checked' : ''}> Send read receipts</label><label><input type="checkbox" id="privacyPhoto" ${current.privacy?.photo !== false ? 'checked' : ''}> Show profile photo</label><button class="secondary-action" id="savePrivacy">Save privacy settings</button><hr><p><strong>Account</strong><br>${esc(auth.currentUser.email || '')}</p></div>`;
  document.getElementById('changeProfilePhoto').onclick = () => document.getElementById('profilePhotoInput').click();
  document.getElementById('profilePhotoInput').onchange = async event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 5 * 1024 * 1024) return toast('Profile photos must be under 5 MB.'); try { const result = await uploadMedia(file, { purpose: 'profile', uid: auth.currentUser.uid }); await updateUserProfile(auth.currentUser.uid, { photoCID: result.cid }); current.photoCID = result.cid; renderProfile(); toast('Profile photo updated.'); } catch (error) { toast(error.message || 'Could not update photo.'); } };
  document.getElementById('saveProfile').onclick = async () => { const button = document.getElementById('saveProfile'); button.disabled = true; try { await updateUserProfile(auth.currentUser.uid, { displayName: document.getElementById('profileDisplayName').value.trim(), username: document.getElementById('profileUsername').value.trim().toLowerCase().replace(/[^a-z0-9_.-]/g, ''), bio: document.getElementById('profileBio').value.trim() }); toast('Profile saved.'); current = await loadProfile(); } catch (error) { toast(error.message || 'Could not save profile.'); } finally { button.disabled = false; } };
  document.getElementById('savePrivacy').onclick = async () => { const button = document.getElementById('savePrivacy'); button.disabled = true; try { await updateDoc(doc(firestore, 'users', auth.currentUser.uid), { privacy: { lastSeen: document.getElementById('privacyLastSeen').checked, online: document.getElementById('privacyOnline').checked, readReceipts: document.getElementById('privacyReadReceipts').checked, photo: document.getElementById('privacyPhoto').checked }, updatedAt: firestoreServerTimestamp() }); toast('Privacy settings saved.'); } catch (error) { toast(error.message || 'Could not save privacy settings.'); } finally { button.disabled = false; } };
}

document.addEventListener('click', event => { if (event.target.closest('#profileButton') || event.target.closest('[data-view="profile"]')) { event.preventDefault(); event.stopImmediatePropagation(); renderProfile().catch(error => toast(error.message || 'Could not load profile.')); } }, true);
